exclude: (^asv_bench|setup.py|requirements-dev.txt)

repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args: ["--disable=import-error"]
        exclude: (^docs/|^scripts)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        entry: mypy pandera tests
        files: (^pandera/|^tests)
        exclude: (^docs/|^scripts)
        pass_filenames: false
