repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
        args: ["--disable=import-error"]
        exclude: (^docs/|^scripts|setup.py)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        entry: mypy pandera tests
        files: (^pandera/|^tests)
        exclude: (^docs/|^scripts)
        pass_filenames: false
