language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n ci-env python=$TRAVIS_PYTHON_VERSION
  - source activate ci-env
  - conda install -y -c conda-forge --file requirements.txt
  - python setup.py install
script:
  - pytest --cov=pandera tests/
  - codecov
  # Check conformity to flake8 style guide
  - flake8 pandera/pandera.py tests
  # Check docs can build, treating warnings as errors
  - python -m sphinx -E -W "docs/source" "docs/_build"
