name: pandera-dev
channels:
  - defaults
  - conda-forge
dependencies:
  # environment management
  - pip

  # documentation
  - sphinx >= 3.2.0
  - sphinx_rtd_theme

  # testing
  - isort >= 5.6.4
  - codecov
  - mypy
  - pylint>=2.4.4
  - pytest
  - pytest-cov

  # packaging
  - twine

# performance testing
  - asv

  # optional
  - pre_commit

  # pandera dependencies
  - black
  - numpy
  - pandas
  - scipy
  - wrapt
  - pyyaml
  - typing_inspect
  - typing_extensions

  - pip:
    - sphinx_autodoc_typehints
