name: pandera-dev-latest
channels:
  - defaults
  - conda-forge
dependencies:
  # required
  - python

  # environment management
  - pip

  # documentation
  - sphinx
  - sphinx_rtd_theme

  # testing
  - codecov
  - mypy
  - pylint>=2.4.4
  - pytest
  - pytest-cov

  # performance testing
  - asv

  # optional
  - pre-commit

  # pandera dependencies
  - numpy
  - pandas
  - scipy
  - wrapt

  - pip:
    - sphinx_autodoc_typehints