package:
  name: pandera
  version: "0.1.2"

source:
  path: ..

build:
  noarch: python

python:
  - 2.7
  - 3.5
  - 3.6

requirements:
  build:
    - python {{ python }}
    - numpy
    - pandas
    - scipy
    - wrapt
  run:
    - python {{ python }}
    - numpy
    - pandas
    - scipy
    - wrapt

test:
  imports:
    - pandera

about:
  home: https://github.com/cosmicBboy/pandera
  license: MIT
  summary: 'Light-weight and flexible validation for pandas data structures.'
  description: |
     Pandas data structures hide a lot of information, and explicitly
     validating them in production-critical or reproducible research
     settings is a good idea.
  doc_url: https://pandera.readthedocs.io/