name: CI Tests
on: push

jobs:
  ci-tests:
    name: CI Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        env-file: ["./ci/environment_pandas_latest.yml"]
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pandera-dev
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.env-file }}
          auto-activate-base: false
      - name: Conda info
        shell: bash
        run: |
          conda info
          conda list
      - name: Check requirements-dev.txt
        shell: bash
        run: python ./scripts/generate_pip_deps_from_conda.py --compare
      - name: Check isort and black formatting
        shell: bash
        run: |
          isort --line-length=79 --check-only pandera tests
          black --line-length=79 --check pandera tests
      - name: Pylint
        shell: bash
        run: |
          if [ "${{ matrix.python-version }}" == "3.9" ]; then
            # https://github.com/PyCQA/pylint/issues/776
            pylint pandera tests --disable=unsubscriptable-object
          else
            pylint pandera tests
          fi
      - name: Mypy Type Checking
        shell: bash
        run: mypy pandera tests
      - name: Unit Tests
        shell: bash
        run: pytest --hypothesis-profile ci --cov=pandera tests/
      - name: Code Coverage
        shell: bash
        run: codecov
      - name: Check Docs
        shell: bash
        run: python -m sphinx -E -b=doctest "docs/source" "docs/_build"
